project:
task:
log_path:

devices:

data:
  path:
  dblp_path: coauth-DBLP-full-node-labels.txt
  article_length: 6000
  embed_model: fasttext

train:
  path:
  transform:
    size: &SIZE 192
    augmentation_scope: none
    images_normalization: &IMAGES_NORMALIZATION default
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    masks_normalization: &MASKS_NORMALIZATION none
    masks_output_format_type: &MASKS_FORMAT_TYPE long
    size_transform: crop_or_resize

val:
  path: /datasets/extra_space/brats/preprocessed/val_2d
  masks: segmentation
  transform:
    size: 256
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    masks_normalization: *MASKS_NORMALIZATION
    masks_output_format_type: *MASKS_FORMAT_TYPE
    size_transform: resize

model:
  arch: deeplab_v3
  encoder: se_resnext50_32x4d
  classes: 4
  loss:
    - name: mean_iou
      weight: 0.5
    - name: categorical_cross_entropy
      gamma: 1
      class_weights: [0.00398384, 0.37205847, 0.16033528, 0.46362242]
      weight: 0.5
  metrics:
    - dice

num_epochs: 150
batch_size: 16
optimizer:
  name: adam
  lr: [0.0002, 0.001]
#  weight_decay: 0.000001


#scheduler:
#  name: step
#  gamma: 0.2
#  step_size: 10

monitor:
  method: epochs
  interval: 100